### ISSUE TITLE
Preprocessed file link broken

### ISSUE THREAD

**Issue by theblackcat102** [danqi/rc-cnn-dailymail#4]
Hi, is there other alternative links to the preprocessed RC datasets. Since both of the links are dead

**Comment by svjan5** [comment]
Hi, It would be great if the files could be made available elsewhere.

**Comment by theblackcat102** [comment]
@svjan5  I have create a file based on deepmind Q&A dataset and format according to the preprocessing steps. 
[Google Drive Link](https://drive.google.com/file/d/1OICBQjZAfBsCRugBlFjvatee7uVIIEqM/view?usp=sharing)

**Comment by svjan5** [comment]
Thanks a lot @theblackcat102!

**Comment by fzweclipse** [comment]
> @svjan5 I have create a file based on deepmind Q&A dataset and format according to the preprocessing steps. [Google Drive Link](https://drive.google.com/file/d/1OICBQjZAfBsCRugBlFjvatee7uVIIEqM/view?usp=sharing)

请问这个文件还能共享吗？
