### ISSUE TITLE
丹琦老师，数据集链接失效了。

### ISSUE THREAD

**Issue by hpeiyan** [danqi/rc-cnn-dailymail#5]
丹琦老师，我是国内的工程师，最近学习MRC，想跑一下相关模型，发现您提供的两个数据集链接失效了，是否有新的仓库链接提供？感谢！

**Comment by ys2899** [comment]
同样的问题

**Comment by danqi** [comment]
Please download the datasets from http://cs.nyu.edu/~kcho/DMQA/. Our processed ones are just simply concatenation of all data instances and keeping document, question and answer only for our inputs.
